baseURL = 'https://prakh0.github.io/'
languageCode = 'en-us'
title = 'The Full Stack Feed'

[params]
  description = "A blog about technical topics, coding, and math."
  author = "Prakhar Pandey"
  info = ["Full Stack Devloper"]
  avatarurl = "images/avatar.jpg"
  dateFormat = "January 2, 2006"
  colorScheme = "auto"
  
  [[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 1
    url = "https://github.com/prakh0"
  [[params.social]]
    name = "Gitlab"
    icon = "fa-solid fa-laptop-code fa-2x"
    weight = 2
    url = "https://leetcode.com/u/Pandey_Prakahr/"
  [[params.social]]
    name = "Twitter"
    icon = "fa-brands fa-x-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/johndoe/"
  [[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/prakhar-pandey-62886026b/"
  [[params.social]]
    name = "Outlook"
    icon = "fa-solid fa-envelope fa-2x"
    weight = 5
    url = "mailto:prakhar_p@outlook.com"





[module]
  [[module.imports]]
    path = "github.com/luizdepra/hugo-coder"

theme = ["hugo-coder"]

[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Project"
  weight = 2
  url = "project/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"
